image: python:3.7-stretch

stages:
  - test
  - post

#####################################################
#                    Test stage                     #
#####################################################

.tox-template: &tox
  stage: test
  before_script:
    - pip3 install --upgrade pip tox tox-venv
    - useradd -Um buildstream
    - chown -R buildstream:buildstream .
  script:
    - su buildstream -c tox
  variables: &tox-variables
    PY_COLORS: 1
    PYTEST_ADDOPTS: '--color=yes'

tests-py37:
  <<: *tox
  variables:
    <<: *tox-variables
    TOXENV: py37

tests-py36:
  <<: *tox
  image: python:3.6-stretch
  variables:
    <<: *tox-variables
    TOXENV: py36

tests-py35:
  <<: *tox
  image: python:3.5-stretch
  script:
    # Plugins behave weirdly inside tox on Python 3.5 only. To further the
    # weirdness, the tests work fine when preparing the environment separately
    # from running tests.
    - su buildstream -c sh -c 'tox --notest'
    - su buildstream -c tox
  variables:
    <<: *tox-variables
    TOXENV: py35

lint:
  <<: *tox
  variables:
    <<: *tox-variables
    TOXENV: flake8

docs:
  <<: *tox
  variables:
    <<: *tox-variables
    TOXENV: docs
  script:
    - su buildstream -c tox
    - mv doc/build/html public
  artifacts:
    paths:
    - public/

#####################################################
#                  Post stage                       #
#####################################################

pages:
  stage: post
  dependencies:
  - docs
  # XXX: This script section is really a no-op but we need to have it since
  # GitLab CI mandates that the pages script can't be blank.
  script:
  - find public/
  artifacts:
    paths:
    - public/
  only:
  - master
