image: buildstream/testsuite-fedora:28-master-123-7ce6581b

stages:
  - test
  - post

before_script:
  # Diagnostics
  - mount
  - df -h

  # Install build & test dependencies
  - dnf install -y gcc python3-devel
  - pip3 install tox tox-venv

  - adduser -m buildstream
  - chown -R buildstream:buildstream .

#####################################################
#                    Test stage                     #
#####################################################

tests:
  stage: test
  variables:
    PY_COLORS: 1
    TOXENV: py36
  script:
    - su buildstream -c 'tox -- --color=yes'

lint:
  stage: test
  variables:
    PY_COLORS: 1
    TOXENV: flake8
  script:
    - su buildstream -c 'tox'

docs:
  stage: test
  script:
  - pip3 install --user .[doc]
  - pip3 install --user git+https://gitlab.com/BuildStream/buildstream.git
  - make -C doc
  - mv doc/build/html public
  artifacts:
    paths:
    - public/

#####################################################
#                  Post stage                       #
#####################################################

pages:
  stage: post
  dependencies:
  - docs
  # XXX: This script section is really a no-op but we need to have it since
  # GitLab CI mandates that the pages script can't be blank.
  script:
  - find public/
  artifacts:
    paths:
    - public/
  only:
  - master
