image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:30-master-78573898

# Given limited CI resources we use various linux distribution images as proxies for the various
# python versions. The following is the mapping between python versions and the respective linux distributions:
# fedora:30 -> py37
# ubuntu:18 -> py36
# debian:9  -> py35

stages:
  - test
  - post

#####################################################
#                    Test stage                     #
#####################################################

.tox-template: &tox
  stage: test
  script:
    - tox -- --docker
  services:
    - name: docker:dind
  variables: &tox-variables
    DOCKER_HOST: tcp://docker:2375/
    PY_COLORS: 1
    PYTEST_ADDOPTS: '--color=yes'
    DOCKER_TLS_CERTDIR: ""

tests-py37:
  <<: *tox
  variables:
    <<: *tox-variables
    TOXENV: py37

tests-py36:
  <<: *tox
  image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-ubuntu:18.04-master-78779247
  variables:
    <<: *tox-variables
    TOXENV: py36

tests-py35:
  <<: *tox
  image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-debian:9-master-78779247
  variables:
    <<: *tox-variables
    TOXENV: py35

lint:
  <<: *tox
  variables:
    <<: *tox-variables
    TOXENV: flake8, rst-lint

docs:
  <<: *tox
  variables:
    <<: *tox-variables
    TOXENV: docs
  script:
    - tox
    - mv doc/build/html public
  artifacts:
    paths:
    - public/

#####################################################
#                  Post stage                       #
#####################################################

pages:
  stage: post
  dependencies:
  - docs
  # XXX: This script section is really a no-op but we need to have it since
  # GitLab CI mandates that the pages script can't be blank.
  script:
  - find public/
  artifacts:
    paths:
    - public/
  only:
  - master

release:
  stage: post
  before_script:
    - pip3 install --upgrade pip tox
  script:
    - tox -e release
  only:
    - tags
