image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:30-master-94236816

# Given limited CI resources we use various linux distribution images as proxies for the various
# python versions. The following is the mapping between python versions and the respective linux distributions:
# python:3.8-buster -> py38
# fedora:30 -> py37
# ubuntu:18 -> py36
# debian:9  -> py35

stages:
  - test
  - post

#####################################################
#                    Test stage                     #
#####################################################

.tox-template: &tox
  stage: test
  script:
    - tox -- --docker
  services:
    - name: docker:dind
  variables: &tox-variables
    DOCKER_HOST: tcp://docker:2375/
    PY_COLORS: 1
    PYTEST_ADDOPTS: '--color=yes'
    DOCKER_TLS_CERTDIR: ""

tests-py38:
  <<: *tox
  image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-python:3.8-buster-master-105004115
  variables:
    <<: *tox-variables
    TOXENV: py38

tests-py37:
  <<: *tox
  variables:
    <<: *tox-variables
    TOXENV: py37

tests-py36:
  <<: *tox
  image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-ubuntu:18.04-master-94236816
  variables:
    <<: *tox-variables
    TOXENV: py36

tests-py35:
  <<: *tox
  image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-debian:9-master-94236816
  variables:
    <<: *tox-variables
    TOXENV: py35

# Ensure that our tests work fine absence of optional dependencies.
# Currently, this is limited to Docker daemon, so we just disable that service
# for this job.
tests-py35-missing-deps:
  <<: *tox
  image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-debian:9-master-94236816
  script: tox -e py35
  services: []

format-check:
  stage: test
  script:
    - tox -e format-check

lint:
  stage: test
  script:
    - tox -e lint,rst-lint

docs:
  <<: *tox
  variables:
    <<: *tox-variables
    TOXENV: docs
  script:
    - tox
    - mv doc/build/html public
  artifacts:
    paths:
    - public/

#####################################################
#                  Post stage                       #
#####################################################

pages:
  stage: post
  dependencies:
  - docs
  # XXX: This script section is really a no-op but we need to have it since
  # GitLab CI mandates that the pages script can't be blank.
  script:
  - find public/
  artifacts:
    paths:
    - public/
  only:
  - master

release:
  stage: post
  before_script:
    - pip3 install --upgrade pip tox
  script:
    - tox -e release
  only:
    - tags
