image: buildstream/testsuite-fedora:28-master-123-7ce6581b

stages:
  - test
  - docs

before_script:
  # Diagnostics
  - mount
  - df -h

  # Install build & test dependencies
  - dnf install -y gcc python3-devel
  - pip3 install tox tox-venv

  - adduser -m buildstream
  - chown -R buildstream:buildstream .

#####################################################
#                    Test stage                     #
#####################################################

tests:
  stage: test
  variables:
    PY_COLORS: 1
  script:
    - su buildstream -c 'tox -- --color=yes'


# Automatically build documentation, only for merges which land
# on master branch.
#
# Note: We still do not enforce a consistent installation of python2
#       or sphinx, as python2 will significantly grow the backing image.
#

#####################################################
#                  Docs stage                       #
#####################################################

pages:
  stage: docs
  script:
  - dnf install -y python2
  - pip3 install sphinx
  - pip3 install sphinx-click
  - pip3 install sphinx_rtd_theme
  - pip3 install --user .
  - make -C doc
  - mv doc/build/html public
  artifacts:
    paths:
    - public/
  only:
  - master
