name: CI
on: [push]

jobs:
  py-tests:
    name: ${{matrix.task.name}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_version:
          - master-105004115
        task:
          - name: tests-py38
            toxenv: py38
            image_prefix: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-python:3.8-buster-
          - name: tests py37
            toxenv: py37
            image_prefix: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:30-
          - name: tests py36
            toxenv: py36
            image_prefix: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-ubuntu:18.04-
    env:
      # (">-" is a YAML construct, which means the following lines will be concatenated
      # onto a one-line string, with no newline at the end.)
      DOCKER_OPTIONS: >-
        --rm 
        --network=host
        --workdir=/home/bst-plugins-container
        --mount type=bind,source=$(pwd),destination=/home/bst-plugins-container
      DOCKER_ENV_OPTIONS: >-
        -e DOCKER_HOST=tcp://localhost:12375/
        -e DOCKER_TLS_CERTDIR=""
        -e PY_COLORS=1
        -e PYTEST_ADDOPTS='--color=yes'
    
    steps:
      - uses: actions/checkout@v2
      - name: tests
        run: |
          docker run --privileged --rm -p 12375:2375 -p 5000:5000 -e DOCKER_TLS_CERTDIR="" docker:dind &
          docker run ${{env.DOCKER_OPTIONS}} ${{env.DOCKER_ENV_OPTIONS}} \
            -e TOXENV=${{matrix.task.toxenv}} \
            ${{matrix.task.image_prefix}}${{matrix.image_version}} \
            tox -- --docker


  format-check:
    name: format-check
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:30-master-105004115
    steps:
      - uses: actions/checkout@v2
      - name: format-check
        run: tox -e format-check

  lint:
    name: lint
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:30-master-105004115
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: tox -e lint,rst-lint

  docs:
    name: docs
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:30-master-105004115
    steps:
      - uses: actions/checkout@v2
      - name: docs
        run: |
          tox -e docs
          mkdir artifact
          sudo mv doc/build/html artifact/public
      - uses: actions/upload-artifact@v1
        with:
          name: public
          path: artifact
